---
# tasks file for time
- name: "Install ntp client"
  yum:
    name: "{{time_ntp_client}}"
    state: "latest"
  notify: "Restart ntp client"

- name: "Start and enable ntp client"
  service:
    name: "{{time_ntp_daemon}}"
    state: "started"
    enabled: yes

